name: portfolio-infrastructure

services:
  terraform:
    image: waldoibarra/terraform
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?err}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?err}
        AWS_PROFILE: ${TF_VAR_aws_profile:?err}
    environment:
      TF_TOKEN_app_terraform_io: ${TF_TOKEN_app_terraform_io:?err}
      TF_VAR_domain_name: ${TF_VAR_domain_name:?err}
      TF_VAR_hosted_zone_id: ${TF_VAR_hosted_zone_id:?err}
      TF_VAR_aws_profile: ${TF_VAR_aws_profile:?err}
      TF_VAR_Application: ${TF_VAR_Application:?err}
    volumes:
      - .:/app/infrastructure
