#!/usr/bin/env sh
set -e

website_service="website"

echo "Running Terraform linter."
docker container run --rm -v $(PWD)/infrastructure:/data -t ghcr.io/terraform-linters/tflint:v0.43.0

echo "Running TypeScript and CSS linters."
docker compose run -T --rm $website_service npm run ci:lint

echo "Running tests."
docker compose run -T --rm $website_service npm run ci:test

echo "All good. ❤️"
